project:
  type: website

website:
  title: "Ludovic Oudin"
  image: "/files/avatar.jpg"
  description: "Ludovic Oudin is a teacher and researcher"
 
  navbar:
    background: light

    left:
      - text: About
        menu:       
        - text: About me
          href: about.qmd    
        - text: Contact
          href: contact.qmd    
      - text: Research
        menu:
        - text: Publications
          href: publications.qmd
        - text: Projects
          href: projects.qmd  
        - text: PhD supervision
          href: supervision.qmd  
        - text: Awards
          href: awards.qmd  
      - text: Teaching
        menu:
        - text: Sorbonne Univ
          href: teaching.qmd
        - text: e-learning
          href: elearning.qmd  
      - text: Media
        menu:
        - text: Media
          href: media.qmd
    right: 
      - text: CV
        href: files/CV_oudin_en.pdf
        target: _blank 
      - text: <i class="ai ai-orcid ai-1.3x"></i> 
        href: https://orcid.org/0000-0002-3712-0933 
      - text: <i class="ai ai-google-scholar-square ai-1.3x"> </i> 
        href: https://scholar.google.fr/citations?user=Nmj_KbIAAAAJ
      - icon: linkedin
        href: https://www.linkedin.com/in/ludovic-oudin-84090a271
      - icon: github
        href: https://github.com/ludovicoudin
       
  page-navigation: true
  
  search:
    location: navbar
    type: textbox
      
  reader-mode: true
  
  draft-mode: unlinked
  

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"