---
title: "Assimilation of soil moisture into hydrological models: the sequential method"
author: "Aubert, D., Loumagne, C., Oudin, L., Hégarat-Mascle, S. L."
publication: "Canadian Journal Of Remote Sensing"
year: 2003
categories: [Hydrological Model,Floods]
doi: https://doi.org/10.5589/m03-042
---

## Abstract

Improving the accuracy of rainfall–runoff models, and in particular their performance in flood prediction, is a key point of continental hydrology. This paper presents a new approach to these problems by the use of soil moisture data (remote sensing or in situ measurements). A first step is to correct past modeling errors, especially errors in simulated runoff, to obtain a more accurate forecast of runoff. Other significant parameters are the interactions occurring within the soil–vegetation–atmosphere interface, which are dominating factors in the processes of the transformation of rainfall into flow at a catchment-area scale. These phenomena can be integrated in hydrological modeling by introducing soil moisture measurements and thus explicitly taking into account the hydric state of the soil. The hydrological models used are global conceptual models. The methodology that we used is a sequential assimilation procedure, which permits step by step control of the evolution of the model and limits its divergence from the available data (soil moisture and flow). The efficiency of the assimilation procedure in flood prediction is discussed, with a particular focus on the contribution of soil moisture data. The question of the time repetitivity of measurements and its influence on the performance of the modeling is also tackled. L'amélioration de la précision des modèles de pluie–débit, en particulier de leur performance dans la prévision des inondations, est un élément essentiel en hydrologie continentale. Cet article présente une nouvelle approche à ces problèmes basée sur l'utilisation des données d'humidité du sol (données de télédétection ou in situ). Une première démarche consiste à corriger les erreurs passées de modélisation, plus spécifiquement les erreurs dans le débit simulé, afin d'assurer une estimation plus précise du débit. Les autres paramètres significatifs sont les interactions se manifestant à l'intérieur de l'interface sol–végétation–atmosphère, qui sont des facteurs dominants dans les processus de transformation des précipitations en écoulement à l'échelle du bassin versant. Ces phénomènes peuvent être intégrés dans la modélisation hydrologique en introduisant les mesures d'humidité du sol, prenant ainsi explicitement en considération l'état hydrique du sol. Les modèles hydrologiques utilisés sont des modèles conceptuels globaux. La méthodologie que nous utilisons est une procédure d'assimilation séquentielle qui permet un contrôle étape par étape de l'évolution du modèle et qui limite sa divergence par rapport aux données disponibles (humidité du sol et écoulement). L'efficacité de la procédure d'assimilation pour la prévision des inondations est discutée, avec une attention particulière axée sur la contribution des données d'humidité du sol. La question de la répétitivité des mesures et de son influence sur la performance de la modélisation est aussi abordée

## Citation

Aubert, D., Loumagne, C., Oudin, L., & Hégarat-Mascle, S. L. (2003). Assimilation of soil moisture into hydrological models: the sequential method. Canadian Journal of Remote Sensing, 29(6), 711–717. https://doi.org/10.5589/m03-042
