---
title: "Assimilation de données d’humidité des sols pour la prévision de crues : comparaison d’un modèle pluie-débit conceptuel et d’un modèle intégrant une interface sol-végétation-atmosphère"
author: "Weisse, A., Oudin, L., Loumagne, C."
publication: "Revue Des Sciences De L’eau"
year: 2005
categories: [Hydrological Model,Hydrogeology,Model Calibration,Floods]
doi: https://doi.org/10.7202/705503ar
---

## Abstract

Le but de cet article est de présenter une méthodologie de mise à jour des paramètres de modèles pluie-débit en période de crue. Elle a été mise au point afin d'améliorer un des aspects de la gestion des réservoirs dans un contexte opérationnel de protection contre les crues: la réduction des incertitudes sur la prévision des débits. L'originalité de la méthode proposée réside dans le fait que l'on utilise non seulement une information sur les débits mais aussi une information sur l'humidité du sol. L'objectif de l'étude est d'évaluer l'intérêt de l'introduction de cette information supplémentaire. Pour cela, les données d'humidité du sol sont introduites au sein du modèle par l'intermédiaire d'une relation de passage établie entre l'humidité mesurée in situ et l'humidité calculée implicitement ou explicitement par les modèles. Cette méthodologie a été testée dans le cadre du projet européen AIMWATER sur quatre sous-bassins de la Seine en amont de Paris (France). Deux modèles pluie-débit sont utilisés dans cette étude, un modèle conceptuel semi-emprique et un modèle conceptuel couplé à un schéma de surface simulant une interface sol-végétation-atmosphère et permettant de calculer l'évolution de l'humidité du sol à différentes profondeurs. Cette approche comparative étudie l'intérêt d'un tel modèle couplé par rapport au modèle conceptuel semi-empirique sans représentation explicite des phénomènes se produisant à l'interface sol-végétation-atmosphère. Improving the accuracy of rainfall-runoff models and in particular their performances in flood prediction is a key point of continental hydrology. Methods have been developed to improve flood prediction in hydrology based on a better compliance of the model with current observations prior to its use in forecasting mode. This operation has been termed updating in hydrology and assimilation in meteorology. The fundamental idea is that if model predictions diverge from observations at a given time, there is little chance that future estimations will approach correct values. The improvement then comes from a correction of the trajectory of the model based on observations during the period preceding the day when a prediction into the immediate or long-term future is desired. This can be dealt with by a correction of model parameters, which is usually called "parameter updating". The inability of rainfall-runoff models to produce correct streamflow values generally translates into parameter uncertainty. Parameter calibration is the means used by a model structure to adjust to a given set of data. Therefore, a parameter updating methodology seems to be a natural way to amend errors in streamflow values. In this paper, a specific methodology of parameter updating is presented. The main feature of this method is that it does not carry out updating by reference only to recent streamflow observations, as classic procedures do, but also to soil moisture measurements, which can be retrieved daily from TDR probes. Indeed, it appears that the integration of soil moisture data allows better control of the evolution of the model and improves its performances, in particular in terms of forecasting. The aim of the research was to assess the usefulness of this additional soil moisture information. To this end, an approach has been suggested that gradually introduces additional information thanks to a constraint relationship between observed and modelled soil moisture. In fact, soil moisture can be calculated implicitly or explicitly by the model when extracting step-by-step the values of the model's store contents. This methodology was put forward for use in the European AIMWATER project on four catchments within the Seine River basin upstream of Paris (France). The other issue addressed in this paper was whether or not it is necessary to use a model that simulates explicitly the evolution of soil moisture at different depths. One can argue that if the model employed does not feature a store that can be identified closely to the observed soil moisture, there would be no possibility of benefiting from such measurements. On the other hand, it can be argued that if soil moisture is a model output, all the information drawn from soil moisture observations will be directed at improving this specific output at the expense of improving streamflow values. To answer this issue, two models were tested. The first model, GR4j, has no explicit counterpart for soil moisture measurements. The second one, GRHum, has been especially developed to introduce a two-layer soil reservoir that simulates the surface and sub-surface soil moisture. Since the aim of the present research was to analyse different ways of accounting for soil moisture, and to identify the one that offers the best prospects, several tests were carried out, using different relationships between observed and modelled soil moisture. Indeed, TDR probes give point measurements of soil moisture at several depths and several store contents can be taken into account in a constraint relationship. First, for both GR4j and GRHum models, tests showed that performances for flood forecasting are significantly improved when assimilating in situ measurements of soil moisture at a daily time-step, especially for the basins where poor simulations are obtained. It is also noteworthy that performances are very dependent on the items taken into account in a constraint relationship. Secondly, the GRHum model did not appear to be more efficient than the GR4j model when assimilating both streamflow and soil moisture data. However, the GRHum model gave the best results when assimilating only streamflow data, and superficial soil moisture seemed to fit the GRHum better than the GR4j model. Finally, although the tests required perfect foreknowledge of rainfall, the results of the research are encouraging from an operational point of view. Another interesting perspective is provided by the Earth Observation data. Indeed, previous studies have shown that soil moisture can be derived from EO data using, for example, microwave spaceborne Synthetic Aperture Radar (SAR) images (QUESNEY et al., 2000). This type of catchment-scale data could be more relevant than a local measure given by TDR probes (PAUWELS et al., 2002).

## Citation

Weisse, A., Oudin, L., & Loumagne, C. (2005). Assimilation de données d’humidité des sols pour la prévision de crues : comparaison d’un modèle pluie-débit conceptuel et d’un modèle intégrant une interface sol-végétation-atmosphère. Revue Des Sciences de l’eau, 16(2), 173–197. https://doi.org/10.7202/705503ar
