---
title: "A multi-objective calibration framework for rainfall–discharge models applied to karst systems"
author: "Moussu, F., Oudin, L., Plagnes, V., Mangin, A., Bendjoudi, H."
publication: "Journal Of Hydrology"
year: 2011
categories: [Hydrogeology,Model Calibration]
doi: https://doi.org/10.1016/j.jhydrol.2011.01.047
---

## Abstract

This paper assesses the potential of several calibration strategies to meet two objectives: good discharge simulations and the ability to reproduce one functional characteristic. Indeed, although classical rainfall–discharge models are often calibrated based on their efficiency in simulating discharge time series, this does not warrant an optimal representation of certain of the system’s hydrodynamic properties, since these properties are used for water management purposes. Therefore, this paper investigates the trade-off between two objectives: (i) good discharge simulations in terms of the least mean square errors and (ii) the ability to reproduce the autocorrelation function of the discharge time series. For this purpose, we applied two rainfall–discharge models on the Baget karst system, an extensively studied system located in the French Pyrenees. The results show that a single-objective calibration based on the classical Nash and Sutcliffe efficiency (NSE) coefficient gives relatively satisfying modelling results, but the autocorrelation function is systematically overestimated. The proposed multi-objective approach improves the ability of the model to mimic the autocorrelation function without greatly altering the model’s NSE efficiency. Last, the multi-objective framework reduces parameter uncertainty and increases the robustness of the two rainfall–discharge models.

## Citation

Moussu, F., Oudin, L., Plagnes, V., Mangin, A., & Bendjoudi, H. (2011). A multi-objective calibration framework for rainfall–discharge models applied to karst systems. Journal of Hydrology, 400(3–4), 364–376. https://doi.org/10.1016/j.jhydrol.2011.01.047
