---
title: "Hydrological model parameter instability: A source of additional uncertainty in estimating the hydrological impacts of climate change?"
author: "Brigode, P., Oudin, L., Perrin, C."
publication: "Journal Of Hydrology"
year: 2013
categories: [Hydrological Model,Climate Change,Model Calibration]
doi: https://doi.org/10.1016/j.jhydrol.2012.11.012
---

## Abstract

This paper investigates the uncertainty of hydrological predictions due to rainfall-runoff model parameters in the context of climate change impact studies. Two sources of uncertainty were considered: (i) the dependence of the optimal parameter set on the climate characteristics of the calibration period and (ii) the use of several posterior parameter sets over a given calibration period. The first source of uncertainty often refers to the lack of model robustness, while the second one refers to parameter uncertainty estimation based on Bayesian inference. Two rainfall-runoff models were tested on 89 catchments in northern and central France. The two sources of uncertainty were assessed in the past observed period and in future climate conditions. The results show that, given the evaluation approach followed here, the lack of robustness was the major source of variability in streamflow projections in future climate conditions for the two models tested. The hydrological projections generated by an ensemble of posterior parameter sets are close to those associated with the optimal set. Therefore, it seems that greater effort should be invested in improving the robustness of models for climate change impact studies, especially by developing more suitable model structures and proposing calibration procedures that increase their robustness.

## Citation

Brigode, P., Oudin, L., & Perrin, C. (2013). Hydrological model parameter instability: A source of additional uncertainty in estimating the hydrological impacts of climate change? Journal of Hydrology, 476, 410–425. https://doi.org/10.1016/j.jhydrol.2012.11.012
