---
title: "Impact of river bed morphology on discharge and water levels simulated by a 1D Saint–Venant hydraulic model at regional scale"
author: "Saleh, F., Ducharne, A., Flipo, N., Oudin, L., Ledoux, E."
publication: "Journal Of Hydrology"
year: 2013
categories: [Model Calibration,Hydraulics,Floods]
doi: https://doi.org/10.1016/j.jhydrol.2012.10.027
---

## Abstract

River cross-sections data are required to represent channel geometry in hydrodynamic models. In the absence of accurate data at regional scale, simplified or parameterized cross sections are often used, which might affect the performance of the hydrodynamic model. In this study we assess the sensitivity of a 1D Saint–Venant hydraulic model to different types of river morphological data. The question is addressed using a 1D unsteady hydraulic model (HEC-RAS), with lateral inflows provided by the hydro(geo)logical model Eau-Dyssée, to explore a wide spectrum of river geometry scenarios, regarding river bed slopes and cross-sectional shapes. The target scale is the one of the Seine River (France). As a gateway for larger and more complex regional hydro(geo)logical applications, our case-study covers a well-described 89-km reach in a sub-tributary of the Seine River. River morphology is described by high-resolution cross-sections, and Manning’s roughness coefficient (n) is used for calibration against observed discharges and river stages in a mid-reach control point, with satisfactory performances over the 8-year simulation period. The resulting model still simulates realistic discharge hydrographs when forced with degraded channel geometry data, using either fewer cross-sections or approximated ones. In such cases, however, the hydraulic model does not always satisfactorily predict the associated water levels when compared to observations. In certain geometry scenarios, the RMSE between simulated water levels using degraded geometry and observations may go up to 0.3m. The study confirms that the accuracy of predicted water levels and maximum water depths simulated by a Saint–Venant model relies on an accurate representation of channel geometry and bed level slopes along the river reach. From the various scenarios, it appears that the longitudinal description of the bed level profiles has a larger impact on the simulation of water levels than the cross-sectional shapes. This offers interesting implications for flood forecast mapping applications and regional scale models that often use simplified river geometry and Digital Elevation Models (DEMs) built by remote sensing technologies to simulate the water levels.

## Citation

Saleh, F., Ducharne, A., Flipo, N., Oudin, L., & Ledoux, E. (2013). Impact of river bed morphology on discharge and water levels simulated by a 1D Saint–Venant hydraulic model at regional scale. Journal of Hydrology, 476, 169–177. https://doi.org/10.1016/j.jhydrol.2012.10.027
