---
title: "Évaluation de l’impact de l’urbanisation sur la réponse hydrologique de 172 bassins versants américains"
author: "Salavati, B., Oudin, L., Furusho, C., Ribstein, P."
publication: "La Houille Blanche"
year: 2015
categories: [Hydrological Model,Land-use Changes,Urban Hydrology]
doi: https://doi.org/10.1051/lhb/20150033
---

## Abstract

L'anthropisation a de multiples impacts sur les réponses hydrologiques des bassins versants. Ces impacts sont difficiles à quantifier à l'échelle spatiale du bassin versant et les résultats de la littérature sur ce sujet sont assez disparates. L'objectif de cette étude est de faire le lien entre la proportion des surfaces urbaines actuelles (considérées comme moins perméables) et l'évolution des réponses hydrologiques des bassins versants. Ceci pose un important problème lié à la relation entre la variabilité du climat et celle de la réponse hydrologique des bassins. Pour ce faire, le modèle hydrologique GR4J a été utilisé. Cette étude est basée sur l'analyse de 104 bassins versants urbains et 68 bassins non-urbains aux États-Unis. Le débit et la pluie journalière des bassins étudiés ont été collectés pour des périodes de 30 à 70 ans selon les bassins. Dans cette méthode, seul le jeu de paramètres du modèle change d'une période de 5 ans à l'autre et la totalité de la chronique de débit est reconstituée à chaque fois, ce qui permet de s'affranchir de la variabilité du climat entre les périodes de 5 ans. Les premiers résultats montrent que les caractéristiques hydrologiques analysées ne présentent pas de tendance significative pour une majorité de bassins versants urbains et que la proportion de bassins avec tendance significative est relativement similaire pour les bassins urbains et non-urbains. Ces résultats doivent être analysés également en fonction de l'évolution historique de l'occupation de sol. Urbanization and people concentration are suspected to have multiple impacts on the catchments hydrological response. Hydrologically-relevant metric of land-use change and climate variability identification still remain an open scientific question. Besides, at the catchment-scale, urbanization impacts on flow are not easy to quantify and previous studies results appear quite disparate when assessing these impacts. The objective of this study is to investigate potential changes in catchments hydrological responses for the current urban surfaces (considered as less permeable). To this aim, the GR4J model, a conceptual daily 4-parameter hydrological model, was used to simulate discharge. In this study, 104 urban catchments and 68 non-urban catchments in the United States were selected. Streamflow and rainfall data were collected with periods of 30 to 70 years. Ensemble of model parameter sets were calibrated for a sequence of 5 years sub-periods and a simulation is performed with each set of parameters using the entire record period. Results showed that a majority of catchments did not present a significant trend over the record period for the hydrological properties analysed on the studied period for urban and non-urban catchments.

## Citation

Salavati, B., Oudin, L., Furusho, C., & Ribstein, P. (2015). Évaluation de l’impact de l’urbanisation sur la réponse hydrologique de 172 bassins versants américains. La Houille Blanche, 101(3), 51–57. https://doi.org/10.1051/lhb/20150033
