---
title: "Process‐based interpretation of conceptual hydrological model performance using a multinational catchment set"
author: "Poncelet, C., Merz, R., Merz, B., Parajka, J., Oudin, L., Andréassian, V., Perrin, C."
publication: "Water Resources Research"
year: 2017
categories: [Hydrological Model,Evapotranspiration]
doi: https://doi.org/10.1002/2016wr019991
---

## Abstract

Most of previous assessments of hydrologic model performance are fragmented, based on small number of catchments, different methods or time periods and do not link the results to landscape or climate characteristics. This study uses large-sample hydrology to identify major catchment controls on daily runoff simulations. It is based on a conceptual lumped hydrological model (GR6J), a collection of 29 catchment characteristics, a multinational set of 1103 catchments located in Austria, France, and Germany and four runoff model efficiency criteria. Two analyses are conducted to assess how features and criteria are linked: (i) a one-dimensional analysis based on the Kruskal-Wallis test and (ii) a multidimensional analysis based on regression trees and investigating the interplay between features. The catchment features most affecting model performance are the flashiness of precipitation and streamflow (computed as the ratio of absolute day-to-day fluctuations by the total amount in a year), the seasonality of evaporation, the catchment area, and the catchment aridity. Nonflashy, nonseasonal, large, and nonarid catchments show the best performance for all the tested criteria. We argue that this higher performance is due to fewer nonlinear responses (higher correlation between precipitation and streamflow) and lower input and output variability for such catchments. Finally, we show that, compared to national sets, multinational sets increase results transferability because they explore a wider range of hydroclimatic conditions.

## Citation

Poncelet, C., Merz, R., Merz, B., Parajka, J., Oudin, L., Andréassian, V., & Perrin, C. (2017). Process‐based interpretation of conceptual hydrological model performance using a multinational catchment set. Water Resources Research, 53(8), 7247–7268. Portico. https://doi.org/10.1002/2016wr019991
