---
title: "Étude de la sensibilité des paramètres d’un modèle «rural» sur des bassins versants urbanisés"
author: "Saadi, M., Oudin, L., Ribstein, P."
publication: "La Houille Blanche"
year: 2019
categories: [Urban Hydrology]
doi: https://doi.org/10.1051/lhb/2019013
---

## Abstract

Plusieurs modèles peuvent être utilisés pour représenter les processus hydrologiques en milieu urbain. Ces modèles sont développés suivant différentes approches en fonction de l'objectif de modélisation, de l'échelle spatio-temporelle et de la disponibilité des données hydroclimatiques et spatiales. Dans cet article, nous proposons de développer un outil parcimonieux et généralisable à partir d'une structure de modèle non dédié au contexte urbanisé. Dans un premier temps, nous analysons la structure de départ et la sensibilité des paramètres qu'elle contient à la présence de surfaces urbaines dans le bassin versant. Pour ce faire, un échantillon de 365 bassins versants français et américains a été construit. Le modèle est calé sur deux périodes pour chaque bassin versant, donnant ainsi 730 couples bassin-période pour lesquels la fraction urbaine dans le bassin a été déterminée. L'analyse de la sensibilité des paramètres du modèle hydrologique par rapport à cette fraction ainsi que d'autres indicateurs hydrologiques a été effectuée pour une sélection de 416 couples bassin-période, homogènes en surface. Les résultats montrent que les paramètres du modèle et les indicateurs hydrologiques présentent des différences significatives entre un échantillon de bassins versants fortement urbanisés et un échantillon de bassins versants faiblement urbanisés, traduisant des écoulements plus rapides et plus importants sur les bassins fortement urbanisés. Several models can be used in order to represent the hydrological processes in an urbanized catchment. Developing those models has been with respect to modeling objectives, spatiotemporal scale and hydroclimatic and spatial data availability. These models can be explicit, hence complex and data demanding, or rather implicit, but lacking direct linking between the model parameters and the urbanization features. Leaning toward simplicity, we aim at developing an efficient modeling tool that permits implicitly to take into account the spatial configuration (urban landscape vs. natural surfaces) and temporal evolution at the scale of an urbanized hydrological catchment. Development of such tool can be achieved by complexifying step-by-step a starting model structure that is not dedicated to urbanized contexts. Before conducting structure modifications, the first step to take is to determine which model functions can be modified. In this paper, we analyze the initial structure and the sensitivity of the parameters that it contains to the presence of urban surfaces within the catchment. For this end, a large sample of 365 French and American catchments was prepared. These catchments are of various sizes going from 1 to 5000 km2 and represent a large panel of hydroclimatic conditions. The model was calibrated on two periods for each catchment, leading to 730 catchment-period couples for which the fraction of the urban cover was determined. The sensitivity analysis of the model parameters and other hydrological indicators with respect to this fraction was conducted for a selection of area-homogeneous 416 catchment-period couples. The results of this empirical study have shown (1) good model performances at the hourly time step regardless of the urban condition of the catchment and (2) that the model parameters and the hydrological indicators are significantly different with regards to intensively or slightly urbanized catchments, reflecting faster and greater streamflows for intensively urbanized situations.

## Citation

Saadi, M., Oudin, L., & Ribstein, P. (2019). Étude de la sensibilité des paramètres d’un modèle «rural» sur des bassins versants urbanisés. La Houille Blanche, 105(2), 35–43. https://doi.org/10.1051/lhb/2019013
