---
title: "Évolution, modélisation et cartographie des rendements de l’oliveraie dans la province de Jaen en Espagne (1959-2018)"
author: "Arfaoui, F., Cohen, M., Oudin, L., Ronchail, J."
publication: "Climatologie"
year: 2021
categories: [Climate Change]
doi: https://doi.org/10.1051/climat/202118004
---

## Abstract

Les acteurs de l’oléiculture en Andalousie s’interrogent sur l’impact du changement climatique sur leur activité, très importante en termes de surfaces concernées, de production et de revenus. Pour tenter de leur répondre, ce travail décrit tout d’abord l’évolution du climat et des rendements annuels des oliveraies pluviales et irriguées dans la province de Jaén (Andalousie) depuis les années 50. Puis sont réalisées des modélisations des relations entre les rendements pluviaux et irrigués provinciaux et des variables climatiques TerraClimate (à résolution de 4 km), moyennées sur la zone oléicole de la province de Jaén. Enfin, les modèles permettent de calculer puis de cartographier la répartition théorique actuelle des rendements. Les rendements, très variables d’une année sur l’autre, plus élevés dans les vergers irrigués que dans les vergers pluviaux, ont fortement augmenté depuis la fin des années cinquante puis ils se sont stabilisés à partir de la fin des années 1990, avec en moyenne 30 q/ha en pluvial et 51 q/ha en irrigué pour la période 1996-2018. Par ailleurs, les températures, moyennées sur la zone oléicole de la province de Jaén, ont augmenté, surtout les températures diurnes, essentiellement durant la saison chaude. Les précipitations, très variables d’une année sur l’autre, ont diminué de 16% après 1979. Entre 1996 et 2018, les variables qui expliquent le mieux les rendements sont les pluies annuelles et les températures minimales d’automne et d’août dans les oliveraies pluviales, et les pluies et températures minimales d’automne, les températures maximales d’été et les températures minimales de février, dans les oliveraies irriguées. Des valeurs de rendement théoriques en pluvial et en irrigué sont calculées par régression multiple (1996-2018), validées par cross-validation. Les valeurs théoriques sont ensuite cartographiées sur des pixels de 4 km de côté. Si les valeurs simulées et moyennées (1996-2018) sont proches des valeurs provinciales observées, avec une erreur-moyenne de 6 q/ha en irrigué et en pluvial, leur répartition spatiale n’est pas tout à fait cohérente avec quelques informations disponibles à l’échelle communale. Il conviendra donc de perfectionner la modélisation des rendements et leur cartographie avant de passer à l’étape suivante : simuler et cartographier les rendements potentiels futurs, compte tenu du changement climatique, pour disposer d’un outil de discussion avec les oléiculteurs et les aider à préparer l’adaptation de leur activité. Olive growers in Andalusia are concerned about the impact of climate change on their activity, which is very important in terms of surface area, production and income. In an attempt to answer these questions, this work first describes the evolution of climate and annual yields of rainfed and irrigated olive groves in the province of Jaén (Andalusia) since the 1950s. Second, the relationships between rainfed and irrigated yields on one side and climatic variables on the other side are modelled. Finally, the models allow the calculation and mapping of the current theoretical spatial distribution of yields. Yields vary greatly from year to year, but are generally higher in irrigated than in rainfed orchards. Yields have risen sharply since the end of the 1950s, stabilizing since the end of the 1990s, with an average over the 1996-2018 period of 30 q/ha and 51 q/ha in irrigated and rainfed areas, respectively. Meanwhile, the mean temperatures over the olive growing area of the province of Jaén, have increased, especially for daytime and during the hot season. Rainfall, which is highly variable over the studied area, has decreased by 16% after 1979. Between 1996 and 2018, the climatic variables explaining best olive yields for rainfed areas are annual rainfall and minimum temperatures in autumn and August. Concerning irrigated areas, autumn rainfall and minimum temperatures, maximum summer temperatures and minimum February temperatures are the most relevant climatic variables. Theoretical yield values for rainfed and irrigated olive groves are calculated by multiple regression (1996-2018), validated by cross-validation. Theoretical yield values are then mapped on 4km side pixels. Although the simulated and averaged values (1996-2018) are close to the observed provincial values, with a mean error of 6 q/ha in irrigated and rainfed areas, their spatial distribution is not entirely consistent with some information available at the communal level. It will therefore be necessary to improve the modeling of yields and their mapping before moving on to the next step: simulating and mapping potential future yields, taking into account climate change, in order to have a tool for discussion with olive growers and to help them prepare the adaptation of their activity.

## Citation

Arfaoui, F., Cohen, M., Oudin, L., & Ronchail, J. (2021). Évolution, modélisation et cartographie des rendements de l’oliveraie dans la province de Jaen en Espagne (1959-2018). Climatologie, 18, 4. https://doi.org/10.1051/climat/202118004
