---
title: "Assessing rainfall global products reliability for water resource management in a tropical volcanic mountainous catchment"
author: "Dumont, M., Saadi, M., Oudin, L., Lachassagne, P., Nugraha, B., Fadillah, A., Bonjour, J., Muhammad, A., Hendarmawan, ., Dörfliger, N., Plagnes, V."
publication: "Journal Of Hydrology: Regional Studies"
year: 2022
categories: [Precipitation]
doi: https://doi.org/10.1016/j.ejrh.2022.101037
---

## Abstract

Water resource management relies fundamentally on our ability to monitor climate forcing variability, especially in tropical mountainous environment where the temporal and spatial variability of rainfall strongly controls the dynamics of the water resource. In West Java Island, rainfall temporal and spatial distribution significantly varies in function of regional climatology and volcanoes morphology while accessibility issues and the complexity of climatic phenomena notably are limitations for reliable rainfall ground instrumentation.

## Citation

Dumont, M., Saadi, M., Oudin, L., Lachassagne, P., Nugraha, B., Fadillah, A., Bonjour, J.-L., Muhammad, A., Hendarmawan, Dörfliger, N., & Plagnes, V. (2022). Assessing rainfall global products reliability for water resource management in a tropical volcanic mountainous catchment. Journal of Hydrology: Regional Studies, 40, 101037. https://doi.org/10.1016/j.ejrh.2022.101037
---
title: "Assessing rainfall global products reliability for water resource management in a tropical volcanic mountainous catchment"
author: "Dumont, M., Saadi, M., Oudin, L., Lachassagne, P., Nugraha, B., Fadillah, A., Bonjour, J., Muhammad, A., Hendarmawan, ., Dörfliger, N., Plagnes, V."
publication: "Journal Of Hydrology: Regional Studies"
year: 2022
categories: [Precipitation]
doi: https://doi.org/10.1016/j.ejrh.2022.101037
---

## Abstract

Here, we assess the ability of climate reanalyses (CHELSA and TerraClimate) and satellite products (CHIRPS) in capturing rainfall high resolution spatial variability. The accuracy of rainfall amounts, variability and dynamics of each global product is estimated using the three component of Kling-Gupta efficiency score. As direct statistical comparison is influenced by …

## Citation

Dumont, M., Saadi, M., Oudin, L., Lachassagne, P., Nugraha, B., Fadillah, A., Bonjour, J.-L., Muhammad, A., Hendarmawan, Dörfliger, N., & Plagnes, V. (2022). Assessing rainfall global products reliability for water resource management in a tropical volcanic mountainous catchment. Journal of Hydrology: Regional Studies, 40, 101037. https://doi.org/10.1016/j.ejrh.2022.101037
